// Shared content for all variants — single source of truth.
const PAUL = {
  name: "Paul Enno Burlon",
  initials: "PEB",
  tagline: "M.A. Sociology · Ludwig-Maximilians-Universität München",
  shortTagline: "Sociology M.A.",
  location: "Munich, DE",
  bio: "Bachelor's thesis examined marriage-market dynamics among refugees in Germany. Prior work at Otto, BIK, MZES, and GESIS — spanning people analytics, market research, migration panel studies, and survey methodology. Outside research: running, road cycling, and piano.",
  bioShort: "Quantitative inequality research, computational social science, survey methodology.",
  email: "pauleburlon@gmail.com",
  links: {
    linkedin: "https://www.linkedin.com/in/paul-burlon",
    github: "https://github.com/pauleburlon",
    cv: "/CV_Paul_Burlon_EN.pdf",
  },
  thesis: {
    title: "Status Maximization via Marriage",
    subtitle: "Refugees' Partnership Preferences",
    meta: "B.A. thesis · University of Mannheim · 2025",
    abstract:
      "Examines whether refugees in Germany show partner preferences consistent with status-maximization strategies, drawing on survey data and multivariate analysis of stated-preference scenarios.",
    keywords: ["Marriage markets", "Forced migration", "Stated preferences", "Multivariate analysis"],
    // Synthetic illustrative coefficients (placeholder until real numbers land)
    findings: [
      { label: "Higher education", coef: 0.42, ci: 0.08 },
      { label: "Same origin region", coef: 0.31, ci: 0.07 },
      { label: "Religious match", coef: 0.18, ci: 0.09 },
      { label: "German fluency", coef: 0.37, ci: 0.10 },
      { label: "Income above median", coef: 0.24, ci: 0.08 },
    ],
  },
  education: [
    {
      place: "Ludwig-Maximilians-Universität München",
      shortPlace: "LMU München",
      date: "10/2025 – present",
      year: "2025—",
      role: "M.A. Sociology",
      city: "Munich, DE",
      bullets: ["Focus on quantitative inequality research"],
      current: true,
    },
    {
      place: "University of Mannheim",
      shortPlace: "U Mannheim",
      date: "09/2021 – 01/2025",
      year: "2021—25",
      role: "B.A. Sociology, Minor in Applied Computer Science",
      grade: "1.7",
      city: "Mannheim, DE",
      bullets: ["Empirical research, data science, quantitative analysis."],
    },
    {
      place: "Singapore Management University",
      shortPlace: "SMU",
      date: "09/2023 – 04/2024",
      year: "2023—24",
      role: "Exchange · B.A. Sociology & B.Sc. Computer Science",
      grade: "2.9 / 4.0",
      city: "Singapore",
      bullets: [
        "PROMOS scholarship (BMBF / DAAD).",
        "Big Data Analytics, Social Networks, advanced methods.",
      ],
    },
    {
      place: "Marion Dönhoff Gymnasium",
      shortPlace: "MDG Hamburg",
      date: "2020",
      year: "2020",
      role: "Abitur",
      grade: "1.9",
      city: "Hamburg, DE",
      bullets: ["Exchange year at Scranton High School (USA); short exchange Oundle School (UK)."],
    },
  ],
  experience: [
    {
      place: "Otto GmbH & Co. KGaA",
      date: "04/2025 – 10/2025",
      year: "2025",
      role: "Internship, People Development",
      city: "Hamburg",
      bullets: [
        "Designed and evaluated executive leadership programs through data-driven approaches.",
        "Supported the rebuild of the company-wide job architecture.",
      ],
      tag: "People analytics",
    },
    {
      place: "BIK Aschpurwis + Behrens GmbH",
      date: "02/2025 – 04/2025",
      year: "2025",
      role: "Internship, Market Research",
      city: "Hamburg",
      bullets: [
        "Descriptive & multivariate analysis identifying success factors in firm cooperation (for a dissertation).",
        "Data visualisations and analytical reports in R / SPSS.",
      ],
      tag: "Market research",
    },
    {
      place: "Mannheimer Zentrum für Europäische Sozialforschung",
      shortPlace: "MZES",
      date: "09/2023 – 01/2025",
      year: "2023—25",
      role: "Student Assistant, PARFORM",
      city: "Mannheim (remote)",
      bullets: [
        "EU-funded panel study on migration and social integration.",
        "Literature research; data cleaning in R / Stata.",
        "Helped develop a new dataset on refugees in Germany.",
      ],
      tag: "Migration research",
    },
    {
      place: "GESIS — Leibniz-Institut für Sozialwissenschaften",
      shortPlace: "GESIS",
      date: "07/2022 – 06/2023",
      year: "2022—23",
      role: "Student Assistant, Survey Design & Methodology",
      city: "Mannheim",
      bullets: [
        "Helped establish the GESIS Puls Survey Panel — digital behaviour ∪ survey responses.",
        "Designed survey items, tested questionnaire logic in pre-fielding phases.",
        "Ran targeted digital ad campaigns to boost respondent engagement.",
      ],
      tag: "Survey methodology",
    },
    {
      place: "L'Arche en Pays Toulousain",
      date: "10/2020 – 08/2021",
      year: "2020—21",
      role: "Volunteer, EIRENE social service",
      city: "Toulouse, FR",
      bullets: [
        "Supported 13 individuals with disabilities as part of a team — helping them achieve personal goals.",
      ],
      tag: "Volunteer",
    },
  ],
  methods: [
    "Regression & multivariate analysis",
    "Panel data analysis",
    "Survey design & questionnaire methodology",
    "Network analysis",
    "Data cleaning & pipeline construction (R, Stata)",
  ],
  skills: {
    programming: ["R", "Python", "Java", "SQL"],
    tools: ["Stata", "SPSS", "Excel", "Unipark"],
    languages: [
      { name: "German", level: "native", pct: 100 },
      { name: "English", level: "fluent · TOEFL 109", pct: 92 },
      { name: "French", level: "intermediate", pct: 60 },
      { name: "Dutch", level: "beginner", pct: 25 },
    ],
  },
  outside: [
    { label: "Running", icon: "run" },
    { label: "Road cycling", icon: "bike" },
    { label: "Piano", icon: "piano" },
  ],
};

window.PAUL = PAUL;
